
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MULT = 21;
  public static final int PARENTESIS_IZQ = 24;
  public static final int CHAR = 9;
  public static final int RES = 20;
  public static final int GRAPHPIE = 44;
  public static final int DOUBLE = 8;
  public static final int DOS_PUNTOS = 10;
  public static final int CORCHETE_DER = 7;
  public static final int GRAPHBAR = 37;
  public static final int TITULOY = 42;
  public static final int TITULOX = 41;
  public static final int EJEY = 40;
  public static final int IDENTIFICADOR = 15;
  public static final int EJEX = 39;
  public static final int IGUAL = 34;
  public static final int COLUMN = 35;
  public static final int ARROBA = 17;
  public static final int TITULO = 38;
  public static final int DIV = 22;
  public static final int GUION = 13;
  public static final int MIN = 31;
  public static final int PUNTO_COMA = 11;
  public static final int MEDIANA = 27;
  public static final int EOF = 0;
  public static final int DECIMAL = 2;
  public static final int PARENTESIS_DER = 25;
  public static final int error = 1;
  public static final int PROGRAM = 3;
  public static final int COMA = 18;
  public static final int CADENA = 14;
  public static final int VALUES = 46;
  public static final int MENOR = 12;
  public static final int MODA = 28;
  public static final int MOD = 23;
  public static final int MAYOR = 36;
  public static final int CORCHETE_IZQ = 6;
  public static final int VARIANZA = 29;
  public static final int END = 4;
  public static final int SUM = 19;
  public static final int ARR = 16;
  public static final int MEDIA = 26;
  public static final int EXEC = 43;
  public static final int LABEL = 45;
  public static final int MAX = 30;
  public static final int HISTOGRAM = 48;
  public static final int GRAPHLINE = 47;
  public static final int VAR = 5;
  public static final int PRINT = 33;
  public static final int CONSOLE = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DECIMAL",
  "PROGRAM",
  "END",
  "VAR",
  "CORCHETE_IZQ",
  "CORCHETE_DER",
  "DOUBLE",
  "CHAR",
  "DOS_PUNTOS",
  "PUNTO_COMA",
  "MENOR",
  "GUION",
  "CADENA",
  "IDENTIFICADOR",
  "ARR",
  "ARROBA",
  "COMA",
  "SUM",
  "RES",
  "MULT",
  "DIV",
  "MOD",
  "PARENTESIS_IZQ",
  "PARENTESIS_DER",
  "MEDIA",
  "MEDIANA",
  "MODA",
  "VARIANZA",
  "MAX",
  "MIN",
  "CONSOLE",
  "PRINT",
  "IGUAL",
  "COLUMN",
  "MAYOR",
  "GRAPHBAR",
  "TITULO",
  "EJEX",
  "EJEY",
  "TITULOX",
  "TITULOY",
  "EXEC",
  "GRAPHPIE",
  "LABEL",
  "VALUES",
  "GRAPHLINE",
  "HISTOGRAM"
  };
}

