/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import Analizadores.Analizador_Lexico;
import Analizadores.Parser;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.JOptionPane;
import main.TablaSimbolos;
import main.Token;

/**
 *
 * @author Fernando
 */
public class Codigo extends javax.swing.JInternalFrame {

    /**
     * Creates new form Codigo
     */
    public Codigo(Principal principal) {
        initComponents();
        this.principal = principal;
    }
    
    String filePath;
    Principal principal;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtEntradaCodigo = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnGuardar = new javax.swing.JMenuItem();
        btnCerrar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnEjecutar = new javax.swing.JMenuItem();
        btnTokens = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        btnErrores = new javax.swing.JMenuItem();
        btnReporteTablas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setClosable(true);
        setIconifiable(true);
        setTitle("Editor de codigo");

        txtEntradaCodigo.setColumns(20);
        txtEntradaCodigo.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtEntradaCodigo.setRows(5);
        jScrollPane1.setViewportView(txtEntradaCodigo);

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jMenu1.setText("Archivo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(btnGuardar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jMenu1.add(btnCerrar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        btnEjecutar.setText("Ejecutar");
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });
        jMenu2.add(btnEjecutar);

        jMenuBar1.add(jMenu2);

        btnTokens.setText("Reportes");

        jMenuItem2.setText("Reporte tokens");
        btnTokens.add(jMenuItem2);

        btnErrores.setText("Reporte errores");
        btnTokens.add(btnErrores);

        btnReporteTablas.setText("Reporte tabla de simbolos");
        btnTokens.add(btnReporteTablas);

        jMenuBar1.add(btnTokens);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.saveFile();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        Principal.listaTokens.clear();
        
        try {
            String text = this.txtEntradaCodigo.getText();
            System.out.println(text);
            Analizador_Lexico scanner = new Analizador_Lexico(new BufferedReader(new StringReader(text)));
            Parser parser = new Parser(scanner);
            parser.parse();
            parser.imprimirVariables();
            parser.imprimirArreglos();
        } catch (Exception e) {
          //  System.out.println(e);
          e.printStackTrace();
        }
        
        System.out.println("********Imprimiendo Tokens*******");
        for(Token token : Principal.listaTokens){
            System.out.println("Tipo: " + token.getTipo() + " Lexema: " + token.getLexema() + " Fila: " + token.getFila() + " Columna: " + token.getColumna());
        }
        
     
    }//GEN-LAST:event_btnEjecutarActionPerformed

    public void agregarCodigoTextArea(String codigo, String filePath){
        
        this.txtEntradaCodigo.append(codigo);
        this.filePath = filePath;
        this.setTitle(filePath);
    
    }
    
    public void saveFile() {
        if (this.filePath != null) {
            try (BufferedWriter writer = new BufferedWriter(new FileWriter(filePath))) {
                writer.write(txtEntradaCodigo.getText());
                JOptionPane.showMessageDialog(null, "Archivo guardado exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar el archivo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "No hay un archivo abierto para guardar", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCerrar;
    private javax.swing.JMenuItem btnEjecutar;
    private javax.swing.JMenuItem btnErrores;
    private javax.swing.JMenuItem btnGuardar;
    private javax.swing.JMenuItem btnReporteTablas;
    private javax.swing.JMenu btnTokens;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtEntradaCodigo;
    // End of variables declaration//GEN-END:variables
}
